Traceback (most recent call last):
  File "C:\Users\artem.tyubaev\Downloads\SKAMEYKA-main\callback.py", line 534, in UpdateDict
    sql = f"INSERT INTO skameyka.user_table (username, password, fullname, relevant, admin) VALUES " \
KeyError: 'UserLogin'
Traceback (most recent call last):
  File "C:\Users\artem.tyubaev\Downloads\SKAMEYKA-main\callback.py", line 534, in UpdateDict
    sql = f"INSERT INTO skameyka.user_table (username, password, fullname, relevant, admin) VALUES " \
KeyError: 'UserLogin'
